monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        messenger:
            type: stream
            path: "%kernel.logs_dir%/messenger.%kernel.environment%.log"
            level: debug
            channels: ["messenger_audit"]
        health_check:
            type: stream
            path: "%kernel.logs_dir%/health-check.%kernel.environment%.log"
            level: debug
            channels: ["health_check"]
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
