services:
    _defaults:
        autowire: true
        autoconfigure: true

    app.message_dispatcher.get.configuration:
        class: App\Model\MachineRequestDispatcherConfiguration
        arguments:
            $dispatchDelayInSeconds: '%update_machine_dispatch_delay%'
            $enabled: false
