# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    digitalocean_access_token: '%env(DIGITALOCEAN_ACCESS_TOKEN)%'
    digitalocean_droplet_name_prefix: '%env(DIGITALOCEAN_NAME_PREFIX)%'
    digitalocean_droplet_region: '%env(DIGITALOCEAN_REGION)%'
    digitalocean_droplet_size: '%env(DIGITALOCEAN_SIZE)%'
    digitalocean_droplet_image: '%env(DIGITALOCEAN_IMAGE)%'
    digitalocean_droplet_tag: '%env(DIGITALOCEAN_TAG)%'
    create_retry_limit: '%env(CREATE_RETRY_LIMIT)%'
    update_worker_dispatch_delay: '%env(UPDATE_WORKER_DISPATCH_DELAY)%'
    update_retry_limit: '%env(UPDATE_RETRY_LIMIT)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    GuzzleHttp\HandlerStack:
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']

    GuzzleHttp\Client:
        class: GuzzleHttp\Client
        arguments:
            $config:
                handler: '@GuzzleHttp\HandlerStack'

    DigitalOceanV2\Client:
        class: DigitalOceanV2\Client
        factory: ['DigitalOceanV2\Client', 'createWithHttpClient']
        arguments:
            $httpClient: '@GuzzleHttp\Client'
        calls:
            - authenticate: ['%digitalocean_access_token%']

    DigitalOceanV2\Api\Droplet:
        class: DigitalOceanV2\Api\Droplet

    app.digitalocean.droplet_configuration.default:
        class: App\Model\DigitalOcean\DropletConfiguration
        arguments:
            $region: '%digitalocean_droplet_region%'
            $size: '%digitalocean_droplet_size%'
            $image: '%digitalocean_droplet_image%'
            $tags:
                - '%digitalocean_droplet_tag%'

    App\Services\MachineProvider\DigitalOcean\DigitalOceanMachineProvider:
        arguments:
            $dropletConfiguration: '@app.digitalocean.droplet_configuration.default'
            $prefix: '%digitalocean_droplet_name_prefix%'

    App\Services\MachineProvider:
        arguments:
            $machineProviders:
                - '@App\Services\MachineProvider\DigitalOcean\DigitalOceanMachineProvider'

    App\Services\ApiActionRetryDecider:
        arguments:
            $deciders:
                - '@App\Services\ApiActionRetryDecider\DigitalOcean\DigitalOceanApiActionRetryDecider'

    app.message_dispatcher.create:
        class: App\MessageDispatcher\WorkerRequestMessageDispatcher

    app.message_dispatcher.update_worker:
        class: App\MessageDispatcher\WorkerRequestMessageDispatcher
        arguments:
            $dispatchDelayInSeconds: '%update_worker_dispatch_delay%'

    App\Services\CreateMachineHandler:
        arguments:
            $createDispatcher: '@app.message_dispatcher.create'
            $updateWorkerDispatcher: '@app.message_dispatcher.update_worker'
            $retryLimit: '%create_retry_limit%'

    App\Services\UpdateWorkerHandler:
        arguments:
            $updateWorkerDispatcher: '@app.message_dispatcher.update_worker'
            $retryLimit: '%update_retry_limit%'

    app.services.worker_state_transition_sequence.create_failed:
        class: App\Model\Worker\StateTransitionSequence
        arguments:
            $states:
                - !php/const App\Model\Worker\State::VALUE_CREATE_RECEIVED
                - !php/const App\Model\Worker\State::VALUE_CREATE_REQUESTED
                - !php/const App\Model\Worker\State::VALUE_CREATE_FAILED

    app.services.worker_state_transition_sequence.delete_failed:
        class: App\Model\Worker\StateTransitionSequence
        arguments:
            $states:
                - !php/const App\Model\Worker\State::VALUE_CREATE_RECEIVED
                - !php/const App\Model\Worker\State::VALUE_CREATE_REQUESTED
                - !php/const App\Model\Worker\State::VALUE_UP_STARTED
                - !php/const App\Model\Worker\State::VALUE_UP_ACTIVE
                - !php/const App\Model\Worker\State::VALUE_DELETE_RECEIVED
                - !php/const App\Model\Worker\State::VALUE_DELETE_REQUESTED
                - !php/const App\Model\Worker\State::VALUE_DELETE_FAILED

    app.services.worker_state_transition_sequence.delete_deleted:
        class: App\Model\Worker\StateTransitionSequence
        arguments:
            $states:
                - !php/const App\Model\Worker\State::VALUE_CREATE_RECEIVED
                - !php/const App\Model\Worker\State::VALUE_CREATE_REQUESTED
                - !php/const App\Model\Worker\State::VALUE_UP_STARTED
                - !php/const App\Model\Worker\State::VALUE_UP_ACTIVE
                - !php/const App\Model\Worker\State::VALUE_DELETE_RECEIVED
                - !php/const App\Model\Worker\State::VALUE_DELETE_REQUESTED
                - !php/const App\Model\Worker\State::VALUE_DELETE_DELETED

    App\Services\WorkerStateTransitionSequences:
        arguments:
            $sequences:
                create_failed: '@app.services.worker_state_transition_sequence.create_failed'
                delete_failed: '@app.services.worker_state_transition_sequence.delete_failed'
                delete_deleted: '@app.services.worker_state_transition_sequence.delete_deleted'
