services:
    _defaults:
        autowire: true
        autoconfigure: true

    app.message_dispatcher.update_worker:
        class: App\MessageDispatcher\MachineRequestMessageDispatcher
        arguments:
            $dispatchDelayInSeconds: '%update_worker_dispatch_delay%'
            $enabled: false
