# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    digitalocean_access_token: '%env(DIGITALOCEAN_ACCESS_TOKEN)%'
    digitalocean_droplet_name_prefix: '%env(DIGITALOCEAN_NAME_PREFIX)%'
    digitalocean_droplet_region: '%env(DIGITALOCEAN_REGION)%'
    digitalocean_droplet_size: '%env(DIGITALOCEAN_SIZE)%'
    digitalocean_droplet_image: '%env(DIGITALOCEAN_IMAGE)%'
    digitalocean_droplet_tag: '%env(DIGITALOCEAN_TAG)%'
    create_retry_limit: '%env(CREATE_RETRY_LIMIT)%'
    update_machine_dispatch_delay: '%env(UPDATE_MACHINE_DISPATCH_DELAY)%'
    get_retry_limit: '%env(GET_RETRY_LIMIT)%'
    machine_exists_dispatch_delay: '%env(MACHINE_EXISTS_DISPATCH_DELAY)%'
    machine_exists_initial_dispatch_delay: '%env(MACHINE_EXISTS_INITIAL_DISPATCH_DELAY)%'
    exists_retry_limit: '%env(EXISTS_RETRY_LIMIT)%'
    machine_is_active_dispatch_delay: '%env(MACHINE_IS_ACTIVE_DISPATCH_DELAY)%'
    delete_retry_limit: '%env(DELETE_RETRY_LIMIT)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Message/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    GuzzleHttp\HandlerStack:
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']

    GuzzleHttp\Client:
        class: GuzzleHttp\Client
        arguments:
            $config:
                handler: '@GuzzleHttp\HandlerStack'

    DigitalOceanV2\Client:
        class: DigitalOceanV2\Client
        factory: ['DigitalOceanV2\Client', 'createWithHttpClient']
        arguments:
            $httpClient: '@GuzzleHttp\Client'
        calls:
            - authenticate: ['%digitalocean_access_token%']

    DigitalOceanV2\Api\Droplet:
        class: DigitalOceanV2\Api\Droplet

    app.digitalocean.droplet_configuration.default:
        class: App\Model\DigitalOcean\DropletConfiguration
        arguments:
            $region: '%digitalocean_droplet_region%'
            $size: '%digitalocean_droplet_size%'
            $image: '%digitalocean_droplet_image%'
            $tags:
                - '%digitalocean_droplet_tag%'

    App\Services\MachineProvider\DigitalOceanMachineProvider:
        arguments:
            $dropletConfiguration: '@app.digitalocean.droplet_configuration.default'
            $prefix: '%digitalocean_droplet_name_prefix%'

    App\Services\MachineProvider\MachineProvider:
        arguments:
            $machineProviders:
                - '@App\Services\MachineProvider\DigitalOceanMachineProvider'

    App\Services\RemoteRequestRetryDecider:
        arguments:
            $deciders:
                - '@App\Services\RemoteRequestRetryDecider\DigitalOcean\DigitalOceanRemoteRequestRetryDecider'
            $retryLimits:
              !php/const App\Model\RemoteRequestActionInterface::ACTION_CREATE: '%create_retry_limit%'
              !php/const App\Model\RemoteRequestActionInterface::ACTION_GET: '%get_retry_limit%'
              !php/const App\Model\RemoteRequestActionInterface::ACTION_EXISTS: '%exists_retry_limit%'
              !php/const App\Model\RemoteRequestActionInterface::ACTION_DELETE: '%delete_retry_limit%'


    app.message_dispatcher.exists.configuration:
        class: App\Model\MachineRequestDispatcherConfiguration
        arguments:
            $dispatchDelayInSeconds: '%machine_exists_dispatch_delay%'
            $initialDispatchDelayInSeconds: '%machine_exists_initial_dispatch_delay%'

    app.message_dispatcher.machine_is_active.configuration:
        class: App\Model\MachineRequestDispatcherConfiguration
        arguments:
            $dispatchDelayInSeconds: '%machine_is_active_dispatch_delay%'

    App\MessageDispatcher\MachineRequestMessageDispatcher:
        arguments:
            $configurations:
                App\Message\MachineExists: '@app.message_dispatcher.exists.configuration'
                App\Message\CheckMachineIsActive: '@app.message_dispatcher.machine_is_active.configuration'

    App\Services\ExceptionFactory\MachineProvider\ExceptionFactory:
        arguments:
            $factories:
                - '@App\Services\ExceptionFactory\MachineProvider\DigitalOceanExceptionFactory'
                - '@App\Services\ExceptionFactory\MachineProvider\GuzzleExceptionFactory'
