services:
    _defaults:
        autowire: true
        autoconfigure: true

    Symfony\Component\Messenger\Transport\InMemoryTransport:
        alias: 'messenger.transport.async'

    App\Tests\Services\Asserter\MessengerAsserter:
        public: true
        arguments:
            $transport: '@messenger.transport.async'

    GuzzleHttp\Handler\MockHandler:
        public: true
        class: GuzzleHttp\Handler\MockHandler

    GuzzleHttp\HandlerStack:
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']
        arguments:
            $handler: '@GuzzleHttp\Handler\MockHandler'

    App\Services\WorkerStateTransitionSequences:
        public: true
        arguments:
            $sequences:
                create_failed: '@app.services.worker_state_transition_sequence.create_failed'
                delete_failed: '@app.services.worker_state_transition_sequence.delete_failed'
                delete_deleted: '@app.services.worker_state_transition_sequence.delete_deleted'

    App\Tests\Services\EntityRefresher:
        public: true
