services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\WorkerFactory:
        public: true

    App\Services\WorkerStore:
        public: true

    App\Services\MachineProvider\DigitalOcean\DigitalOceanMachineProvider:
        public: true

    app.digitalocean.droplet_configuration.default:
        class: App\Model\DigitalOcean\DropletConfiguration
        arguments:
            $region: '%digitalocean_droplet_region%'
            $size: '%digitalocean_droplet_size%'
            $image: '%digitalocean_droplet_image%'

    App\Services\MachineProvider\DigitalOcean\DropletFactory:
        arguments:
            $dropletConfiguration: '@app.digitalocean.droplet_configuration.default'

    App\Services\MachineProvider:
        public: true
        arguments:
            $machineProviders:
                - '@App\Services\MachineProvider\DigitalOcean\DigitalOceanMachineProvider'

    App\Services\CreateFailureRetryDecider:
        public: true
        arguments:
            $deciders:
                - '@App\Services\CreateFailureRetryDecider\DigitalOcean\DigitalOceanCreateFailureRetryDecider'

    Symfony\Component\Messenger\Transport\InMemoryTransport:
        alias: 'messenger.transport.async'

    App\Tests\Services\Asserter\MessengerAsserter:
        public: true
        arguments:
            $transport: '@messenger.transport.async'
