name: Integration Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  integration:
    name: Integration tests - PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8']
    runs-on: ${{ matrix.operating-system }}

    env:
      DATABASE_URL: postgres://postgres:password!@127.0.0.1:5432/basil-worker-db?charset=UTF-8

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: amqp, pgsql

      - name: Download dependencies
        uses: php-actions/composer@v2
        with:
          args: --ignore-platform-reqs --quiet

      - name: Pull images
        run: composer integration-pull

      - name: Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Setup integration environment
        run: composer integration-setup

      - name: Run synchronous tests
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN_TEST }}
        run: composer test-integration-sync

      - name: Run asynchronous tests
        env:
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN_TEST }}
        run: |
          php bin/console --env=integration_async messenger:consume async > /dev/null &
          composer test-integration-async
          php bin/console --env=integration_async messenger:stop
